# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vkoskiv/Documents/dev/c-ray

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vkoskiv/Documents/dev/c-ray

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vkoskiv/Documents/dev/c-ray/CMakeFiles /Users/vkoskiv/Documents/dev/c-ray/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vkoskiv/Documents/dev/c-ray/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c-ray

# Build rule for target.
c-ray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c-ray
.PHONY : c-ray

# fast build rule for target.
c-ray/fast:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/build
.PHONY : c-ray/fast

src/bbox.o: src/bbox.c.o

.PHONY : src/bbox.o

# target to build an object file
src/bbox.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/bbox.c.o
.PHONY : src/bbox.c.o

src/bbox.i: src/bbox.c.i

.PHONY : src/bbox.i

# target to preprocess a source file
src/bbox.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/bbox.c.i
.PHONY : src/bbox.c.i

src/bbox.s: src/bbox.c.s

.PHONY : src/bbox.s

# target to generate assembly for a file
src/bbox.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/bbox.c.s
.PHONY : src/bbox.c.s

src/cJSON.o: src/cJSON.c.o

.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i

.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s

.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/camera.o: src/camera.c.o

.PHONY : src/camera.o

# target to build an object file
src/camera.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/camera.c.o
.PHONY : src/camera.c.o

src/camera.i: src/camera.c.i

.PHONY : src/camera.i

# target to preprocess a source file
src/camera.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/camera.c.i
.PHONY : src/camera.c.i

src/camera.s: src/camera.c.s

.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/camera.c.s
.PHONY : src/camera.c.s

src/color.o: src/color.c.o

.PHONY : src/color.o

# target to build an object file
src/color.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/color.c.o
.PHONY : src/color.c.o

src/color.i: src/color.c.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/color.c.i
.PHONY : src/color.c.i

src/color.s: src/color.c.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/color.c.s
.PHONY : src/color.c.s

src/converter.o: src/converter.c.o

.PHONY : src/converter.o

# target to build an object file
src/converter.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/converter.c.o
.PHONY : src/converter.c.o

src/converter.i: src/converter.c.i

.PHONY : src/converter.i

# target to preprocess a source file
src/converter.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/converter.c.i
.PHONY : src/converter.c.i

src/converter.s: src/converter.c.s

.PHONY : src/converter.s

# target to generate assembly for a file
src/converter.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/converter.c.s
.PHONY : src/converter.c.s

src/filehandler.o: src/filehandler.c.o

.PHONY : src/filehandler.o

# target to build an object file
src/filehandler.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/filehandler.c.o
.PHONY : src/filehandler.c.o

src/filehandler.i: src/filehandler.c.i

.PHONY : src/filehandler.i

# target to preprocess a source file
src/filehandler.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/filehandler.c.i
.PHONY : src/filehandler.c.i

src/filehandler.s: src/filehandler.c.s

.PHONY : src/filehandler.s

# target to generate assembly for a file
src/filehandler.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/filehandler.c.s
.PHONY : src/filehandler.c.s

src/kdtree.o: src/kdtree.c.o

.PHONY : src/kdtree.o

# target to build an object file
src/kdtree.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/kdtree.c.o
.PHONY : src/kdtree.c.o

src/kdtree.i: src/kdtree.c.i

.PHONY : src/kdtree.i

# target to preprocess a source file
src/kdtree.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/kdtree.c.i
.PHONY : src/kdtree.c.i

src/kdtree.s: src/kdtree.c.s

.PHONY : src/kdtree.s

# target to generate assembly for a file
src/kdtree.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/kdtree.c.s
.PHONY : src/kdtree.c.s

src/light.o: src/light.c.o

.PHONY : src/light.o

# target to build an object file
src/light.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/light.c.o
.PHONY : src/light.c.o

src/light.i: src/light.c.i

.PHONY : src/light.i

# target to preprocess a source file
src/light.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/light.c.i
.PHONY : src/light.c.i

src/light.s: src/light.c.s

.PHONY : src/light.s

# target to generate assembly for a file
src/light.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/light.c.s
.PHONY : src/light.c.s

src/lightRay.o: src/lightRay.c.o

.PHONY : src/lightRay.o

# target to build an object file
src/lightRay.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lightRay.c.o
.PHONY : src/lightRay.c.o

src/lightRay.i: src/lightRay.c.i

.PHONY : src/lightRay.i

# target to preprocess a source file
src/lightRay.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lightRay.c.i
.PHONY : src/lightRay.c.i

src/lightRay.s: src/lightRay.c.s

.PHONY : src/lightRay.s

# target to generate assembly for a file
src/lightRay.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lightRay.c.s
.PHONY : src/lightRay.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/list.c.s
.PHONY : src/list.c.s

src/lodepng.o: src/lodepng.c.o

.PHONY : src/lodepng.o

# target to build an object file
src/lodepng.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lodepng.c.o
.PHONY : src/lodepng.c.o

src/lodepng.i: src/lodepng.c.i

.PHONY : src/lodepng.i

# target to preprocess a source file
src/lodepng.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lodepng.c.i
.PHONY : src/lodepng.c.i

src/lodepng.s: src/lodepng.c.s

.PHONY : src/lodepng.s

# target to generate assembly for a file
src/lodepng.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/lodepng.c.s
.PHONY : src/lodepng.c.s

src/logging.o: src/logging.c.o

.PHONY : src/logging.o

# target to build an object file
src/logging.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/logging.c.o
.PHONY : src/logging.c.o

src/logging.i: src/logging.c.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/logging.c.i
.PHONY : src/logging.c.i

src/logging.s: src/logging.c.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/logging.c.s
.PHONY : src/logging.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/main.c.s
.PHONY : src/main.c.s

src/material.o: src/material.c.o

.PHONY : src/material.o

# target to build an object file
src/material.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/material.c.o
.PHONY : src/material.c.o

src/material.i: src/material.c.i

.PHONY : src/material.i

# target to preprocess a source file
src/material.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/material.c.i
.PHONY : src/material.c.i

src/material.s: src/material.c.s

.PHONY : src/material.s

# target to generate assembly for a file
src/material.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/material.c.s
.PHONY : src/material.c.s

src/obj.o: src/obj.c.o

.PHONY : src/obj.o

# target to build an object file
src/obj.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj.c.o
.PHONY : src/obj.c.o

src/obj.i: src/obj.c.i

.PHONY : src/obj.i

# target to preprocess a source file
src/obj.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj.c.i
.PHONY : src/obj.c.i

src/obj.s: src/obj.c.s

.PHONY : src/obj.s

# target to generate assembly for a file
src/obj.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj.c.s
.PHONY : src/obj.c.s

src/obj_parser.o: src/obj_parser.c.o

.PHONY : src/obj_parser.o

# target to build an object file
src/obj_parser.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj_parser.c.o
.PHONY : src/obj_parser.c.o

src/obj_parser.i: src/obj_parser.c.i

.PHONY : src/obj_parser.i

# target to preprocess a source file
src/obj_parser.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj_parser.c.i
.PHONY : src/obj_parser.c.i

src/obj_parser.s: src/obj_parser.c.s

.PHONY : src/obj_parser.s

# target to generate assembly for a file
src/obj_parser.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/obj_parser.c.s
.PHONY : src/obj_parser.c.s

src/pathtrace.o: src/pathtrace.c.o

.PHONY : src/pathtrace.o

# target to build an object file
src/pathtrace.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/pathtrace.c.o
.PHONY : src/pathtrace.c.o

src/pathtrace.i: src/pathtrace.c.i

.PHONY : src/pathtrace.i

# target to preprocess a source file
src/pathtrace.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/pathtrace.c.i
.PHONY : src/pathtrace.c.i

src/pathtrace.s: src/pathtrace.c.s

.PHONY : src/pathtrace.s

# target to generate assembly for a file
src/pathtrace.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/pathtrace.c.s
.PHONY : src/pathtrace.c.s

src/poly.o: src/poly.c.o

.PHONY : src/poly.o

# target to build an object file
src/poly.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/poly.c.o
.PHONY : src/poly.c.o

src/poly.i: src/poly.c.i

.PHONY : src/poly.i

# target to preprocess a source file
src/poly.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/poly.c.i
.PHONY : src/poly.c.i

src/poly.s: src/poly.c.s

.PHONY : src/poly.s

# target to generate assembly for a file
src/poly.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/poly.c.s
.PHONY : src/poly.c.s

src/renderer.o: src/renderer.c.o

.PHONY : src/renderer.o

# target to build an object file
src/renderer.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/renderer.c.o
.PHONY : src/renderer.c.o

src/renderer.i: src/renderer.c.i

.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/renderer.c.i
.PHONY : src/renderer.c.i

src/renderer.s: src/renderer.c.s

.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/renderer.c.s
.PHONY : src/renderer.c.s

src/scene.o: src/scene.c.o

.PHONY : src/scene.o

# target to build an object file
src/scene.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/scene.c.o
.PHONY : src/scene.c.o

src/scene.i: src/scene.c.i

.PHONY : src/scene.i

# target to preprocess a source file
src/scene.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/scene.c.i
.PHONY : src/scene.c.i

src/scene.s: src/scene.c.s

.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/scene.c.s
.PHONY : src/scene.c.s

src/sphere.o: src/sphere.c.o

.PHONY : src/sphere.o

# target to build an object file
src/sphere.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/sphere.c.o
.PHONY : src/sphere.c.o

src/sphere.i: src/sphere.c.i

.PHONY : src/sphere.i

# target to preprocess a source file
src/sphere.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/sphere.c.i
.PHONY : src/sphere.c.i

src/sphere.s: src/sphere.c.s

.PHONY : src/sphere.s

# target to generate assembly for a file
src/sphere.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/sphere.c.s
.PHONY : src/sphere.c.s

src/string_extra.o: src/string_extra.c.o

.PHONY : src/string_extra.o

# target to build an object file
src/string_extra.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/string_extra.c.o
.PHONY : src/string_extra.c.o

src/string_extra.i: src/string_extra.c.i

.PHONY : src/string_extra.i

# target to preprocess a source file
src/string_extra.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/string_extra.c.i
.PHONY : src/string_extra.c.i

src/string_extra.s: src/string_extra.c.s

.PHONY : src/string_extra.s

# target to generate assembly for a file
src/string_extra.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/string_extra.c.s
.PHONY : src/string_extra.c.s

src/transforms.o: src/transforms.c.o

.PHONY : src/transforms.o

# target to build an object file
src/transforms.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/transforms.c.o
.PHONY : src/transforms.c.o

src/transforms.i: src/transforms.c.i

.PHONY : src/transforms.i

# target to preprocess a source file
src/transforms.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/transforms.c.i
.PHONY : src/transforms.c.i

src/transforms.s: src/transforms.c.s

.PHONY : src/transforms.s

# target to generate assembly for a file
src/transforms.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/transforms.c.s
.PHONY : src/transforms.c.s

src/ui.o: src/ui.c.o

.PHONY : src/ui.o

# target to build an object file
src/ui.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/ui.c.o
.PHONY : src/ui.c.o

src/ui.i: src/ui.c.i

.PHONY : src/ui.i

# target to preprocess a source file
src/ui.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/ui.c.i
.PHONY : src/ui.c.i

src/ui.s: src/ui.c.s

.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/ui.c.s
.PHONY : src/ui.c.s

src/vector.o: src/vector.c.o

.PHONY : src/vector.o

# target to build an object file
src/vector.c.o:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/vector.c.o
.PHONY : src/vector.c.o

src/vector.i: src/vector.c.i

.PHONY : src/vector.i

# target to preprocess a source file
src/vector.c.i:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/vector.c.i
.PHONY : src/vector.c.i

src/vector.s: src/vector.c.s

.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.c.s:
	$(MAKE) -f CMakeFiles/c-ray.dir/build.make CMakeFiles/c-ray.dir/src/vector.c.s
.PHONY : src/vector.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... c-ray"
	@echo "... src/bbox.o"
	@echo "... src/bbox.i"
	@echo "... src/bbox.s"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/converter.o"
	@echo "... src/converter.i"
	@echo "... src/converter.s"
	@echo "... src/filehandler.o"
	@echo "... src/filehandler.i"
	@echo "... src/filehandler.s"
	@echo "... src/kdtree.o"
	@echo "... src/kdtree.i"
	@echo "... src/kdtree.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/lightRay.o"
	@echo "... src/lightRay.i"
	@echo "... src/lightRay.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/lodepng.o"
	@echo "... src/lodepng.i"
	@echo "... src/lodepng.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/obj.o"
	@echo "... src/obj.i"
	@echo "... src/obj.s"
	@echo "... src/obj_parser.o"
	@echo "... src/obj_parser.i"
	@echo "... src/obj_parser.s"
	@echo "... src/pathtrace.o"
	@echo "... src/pathtrace.i"
	@echo "... src/pathtrace.s"
	@echo "... src/poly.o"
	@echo "... src/poly.i"
	@echo "... src/poly.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/sphere.o"
	@echo "... src/sphere.i"
	@echo "... src/sphere.s"
	@echo "... src/string_extra.o"
	@echo "... src/string_extra.i"
	@echo "... src/string_extra.s"
	@echo "... src/transforms.o"
	@echo "... src/transforms.i"
	@echo "... src/transforms.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

