//
//  gitsha1.c
//  C-ray
//
//  Created by Valtteri Koskivuori on 7.4.2019.
//  Copyright © 2015-2020 Valtteri Koskivuori. All rights reserved.
//

// Autogenerated - Do not edit

#include "gitsha1.h"
#include <string.h>
#include <stdlib.h>

#define GIT_SHA1 "759b0addc33a7e805e27092763088316ffabb41d"

char *gitHash() {
	return GIT_SHA1;
}
